In [305]:
import matplotlib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', None)
# 한글 폰트 설정 (Windows의 경우, 나눔 고딕 폰트를 사용)
plt.rcParams['font.family'] = 'NanumGothic'

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [307]:
rjfo = pd.read_csv('../data/(1) 월별 순판매량.csv',encoding="cp949")

# # 중분류 라면 추출 및 필요 없는 열 제거 
# 1데이터
rjfo = rjfo[rjfo['중분류'] == '라면,통조림,상온즉석']
# 2데이터
#rjfo = rjfo[rjfo['대분류'] == '면류.라면류']


rjfo = rjfo.drop(['판매수량','반품수량','월','년'],axis='columns')
rjfo.head()

         날짜          중분류   순판매량
3   2021-01  라면,통조림,상온즉석  10585
23  2021-02  라면,통조림,상온즉석  11608
42  2021-03  라면,통조림,상온즉석  15018
59  2021-04  라면,통조림,상온즉석  11667
78  2021-05  라면,통조림,상온즉석  14607

In [308]:
# 원래는 외부 변수만 모은 "유튜브도합친거.csv"를 읽었음. 같은 변수가 든 분석용 변수표에서 판매량 열만 빼고 사용
a = pd.read_csv("../data/최종 변수.csv").drop(columns=["1_순판매량", "2_순판매량"])

# 날짜 열에서 앞의 7자만 남기기
a['날짜'] = a['날짜'].str[:7]

# '날짜' 열에서 앞의 4글자가 '2024'인 행 삭제
a = a[~a['날짜'].str[:4].eq('2024')]


a.head()

,날짜,구글트렌드,코로나확진자,소비자심리지수,판매액,라면지수,소비자물가지수,네이버트렌드,유튜브트렌드
0,2021-01,376,17470.0,95.3,13954387,99.93,101.04,86.09479,403
1,2021-02,292,11466.0,97.4,14004697,99.79,101.58,64.87382,308
2,2021-03,269,13414.0,100.6,12826631,99.95,101.84,96.91420,317
3,2021-04,277,18926.0,102.4,13094898,99.30,101.98,90.08193,321
4,2021-05,356,18329.0,105.5,13620588,99.97,102.05,97.57709,428

In [309]:
# '날짜'를 인덱스로 설정 (필요시 인덱스 설정)
rjfo.set_index('날짜', inplace=True)
a.set_index('날짜', inplace=True)

# 두 데이터프레임을 concat으로 합치기
data = pd.concat([rjfo, a], axis=1)

# 인덱스를 일반 열로 변환
data.reset_index(inplace=True)

# 1데이터
data = data.drop(['중분류','날짜'],axis='columns')

# 2데이터
#data = data.drop(['대분류','날짜'],axis='columns')


data.head()

    순판매량  구글트렌드   코로나확진자  소비자심리지수       판매액   라면지수  소비자물가지수    네이버트렌드  유튜브트렌드
0  10585    376  17470.0     95.3  13954387  99.93   101.04  86.09479     403
1  11608    292  11466.0     97.4  14004697  99.79   101.58  64.87382     308
2  15018    269  13414.0    100.6  12826631  99.95   101.84  96.91420     317
3  11667    277  18926.0    102.4  13094898  99.30   101.98  90.08193     321
4  14607    356  18329.0    105.5  13620588  99.97   102.05  97.57709     428

* 데이터 에서 NA값을 0으로 변경

In [310]:
# 전체 데이터에서 NA 값을 0으로 변경
data = data.fillna(0)

In [292]:
data.head()

,날짜,순판매량,구글트렌드,코로나확진자,소비자심리지수,판매액,라면지수,소비자물가지수,네이버트렌드,유튜브트렌드
0,2021-01,8626,376,17470.0,95.3,13954387,99.93,101.04,86.09479,403
1,2021-02,5642,292,11466.0,97.4,14004697,99.79,101.58,64.87382,308
2,2021-03,8164,269,13414.0,100.6,12826631,99.95,101.84,96.91420,317
3,2021-04,6811,277,18926.0,102.4,13094898,99.30,101.98,90.08193,321
4,2021-05,6707,356,18329.0,105.5,13620588,99.97,102.05,97.57709,428

In [311]:
data.corr()['순판매량'].sort_values(ascending=False)

순판매량       1.000000
판매액        0.388955
소비자물가지수    0.304424
라면지수       0.190201
코로나확진자     0.169379
네이버트렌드     0.158799
유튜브트렌드    -0.016894
구글트렌드     -0.063705
소비자심리지수   -0.064478
Name: 순판매량, dtype: float64